MODEL:
  DEVICE_ID: 0
  TRANSFORMER_TYPE: 'ViT-B-16'
  STRIDE_SIZE: [ 16, 16 ]
  DIRECT: 0
  SIE_COE: 1.0
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  CMI_ALPHA: 0.3
  DROP_PATH: 0.2
  NO_MARGIN: False
  APART: 'off'  
INPUT:
  SIZE_TRAIN: [ 128, 256 ]
  SIZE_TEST: [ 128, 256 ]
  PROB: 0.5
  RE_PROB: 0.0
  PADDING: 10

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_WORKERS: 8
  NUM_INSTANCE: 2

DATASETS:
  NAMES: 'WMVEID863'
  ROOT_DIR: '/data/datasets'


SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.00005
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 32
  MARGIN: 0.5
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 60
  EVAL_PERIOD: 1
  WEIGHT_DECAY: 1e-5
  WEIGHT_DECAY_BIAS: 1e-5
  BIAS_LR_FACTOR: 2
  MAX_EPOCHS: 80
  SEED: 1234
TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'no'
  MISS: "nothing"
  IMS_PER_BATCH: 64

OUTPUT_DIR: './logs/MSV863/c'
