MODEL:
  TRANSFORMER_TYPE: 'ViT-B-16'
  STRIDE_SIZE: [ 16, 16 ]
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  CMI_ALPHA: 0.3
  INFERENCE_FUSION: 'legacy'
  INFERENCE_IMAGE_WEIGHT: 1.0
  INFERENCE_TEXT_WEIGHT: 1.0
  DEBUG_TEXT_ENCODING: False
  ALIGN_LOSS_WEIGHT: 0.05
  ALIGN_TEMPERATURE: 0.07
  NO_MARGIN: False
  APART: 'off'  

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_WORKERS: 8
  NUM_INSTANCE: 4

DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR:  '/data/datasets'
  CATEGORY: "pedestrian" 

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.00035
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 32
  DYNAMIC_MARGIN: False
  MARGIN_START: 0.30
  MARGIN_RAMP_START: 5
  MARGIN_RAMP_END: 15
  MARGIN: 0.3
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY: 5e-2
  WEIGHT_DECAY_BIAS: 0.0
  BIAS_LR_FACTOR: 2
  MAX_EPOCHS: 60
  SEED: 1234
TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: "nothing"
  IMS_PER_BATCH: 128

OUTPUT_DIR: './logs/RGBNT201/current'
