from yacs.config import CfgNode as CN


_C = CN()

_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda"
_C.MODEL.DEVICE_ID = 0
_C.MODEL.NAME = "CoT-ReID"
_C.MODEL.PRETRAIN_CHOICE = "imagenet"
_C.MODEL.PREFIX = ""
_C.MODEL.TRANSFORMER_TYPE = "ViT-B-16"
_C.MODEL.STRIDE_SIZE = [16, 16]
_C.MODEL.DROP_PATH = 0.1
_C.MODEL.DROP_OUT = 0.0
_C.MODEL.ATT_DROP_RATE = 0.0
_C.MODEL.SIE_COE = 3.0
_C.MODEL.SIE_CAMERA = False
_C.MODEL.SIE_VIEW = False
_C.MODEL.DIRECT = 0
_C.MODEL.NECK = "bnneck"
_C.MODEL.APART = "off"
_C.MODEL.FROZEN = False
_C.MODEL.TEXT_PROMPT = 2
_C.MODEL.PROMPT = False
_C.MODEL.ADAPTER = False
_C.MODEL.ID_LOSS_TYPE = "softmax"
_C.MODEL.ID_LOSS_WEIGHT = 1.0
_C.MODEL.TRIPLET_LOSS_WEIGHT = 1.0
_C.MODEL.METRIC_LOSS_TYPE = "triplet"
_C.MODEL.IF_LABELSMOOTH = "on"
_C.MODEL.NO_MARGIN = False
_C.MODEL.DIST_TRAIN = False
_C.MODEL.CMI_ALPHA = 0.6
_C.MODEL.CMI_N0 = 3
_C.MODEL.CMI_N1 = 1
_C.MODEL.INFERENCE_FUSION = "legacy"
_C.MODEL.INFERENCE_IMAGE_WEIGHT = 1.0
_C.MODEL.INFERENCE_TEXT_WEIGHT = 1.0
_C.MODEL.DEBUG_TEXT_ENCODING = False
_C.MODEL.ALIGN_LOSS_WEIGHT = 0.0
_C.MODEL.ALIGN_TEMPERATURE = 0.07

_C.INPUT = CN()
_C.INPUT.SIZE_TRAIN = [256, 128]
_C.INPUT.SIZE_TEST = [256, 128]
_C.INPUT.PROB = 0.5
_C.INPUT.RE_PROB = 0.0
_C.INPUT.PIXEL_MEAN = [0.485, 0.456, 0.406]
_C.INPUT.PIXEL_STD = [0.229, 0.224, 0.225]
_C.INPUT.PADDING = 10

_C.DATASETS = CN()
_C.DATASETS.NAMES = "RGBNT201"
_C.DATASETS.ROOT_DIR = "./data"
_C.DATASETS.CATEGORY = "vehicle"
_C.DATASETS.TEXT_DIR = ""

_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 8
_C.DATALOADER.SAMPLER = "softmax_triplet"
_C.DATALOADER.NUM_INSTANCE = 4

_C.SOLVER = CN()
_C.SOLVER.OPTIMIZER_NAME = "Adam"
_C.SOLVER.MAX_EPOCHS = 100
_C.SOLVER.BASE_LR = 3e-4
_C.SOLVER.IMS_PER_BATCH = 64
_C.SOLVER.SEED = 1111
_C.SOLVER.BIAS_LR_FACTOR = 2
_C.SOLVER.LARGE_FC_LR = False
_C.SOLVER.MOMENTUM = 0.9
_C.SOLVER.MARGIN = 0.3
_C.SOLVER.DYNAMIC_MARGIN = False
_C.SOLVER.MARGIN_START = 0.3
_C.SOLVER.MARGIN_RAMP_START = 5
_C.SOLVER.MARGIN_RAMP_END = 15
_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.WEIGHT_DECAY_BIAS = 0.0005
_C.SOLVER.CENTER_LR = 0.5
_C.SOLVER.CENTER_LOSS_WEIGHT = 0.0005
_C.SOLVER.WARMUP_EPOCHS = 5
_C.SOLVER.WARMUP_ITERS = 10
_C.SOLVER.LR_MIN = 0.000016
_C.SOLVER.CHECKPOINT_PERIOD = 10
_C.SOLVER.LOG_PERIOD = 100
_C.SOLVER.EVAL_PERIOD = 10

_C.TEST = CN()
_C.TEST.IMS_PER_BATCH = 256
_C.TEST.RE_RANKING = "no"
_C.TEST.RE_RANKING_K1 = 20
_C.TEST.RE_RANKING_K2 = 6
_C.TEST.RE_RANKING_LAMBDA = 0.3
_C.TEST.WEIGHT = ""
_C.TEST.NECK_FEAT = "before"
_C.TEST.FEAT_NORM = "yes"
_C.TEST.MISS = "nothing"
_C.TEST.FEAT = 0

_C.OUTPUT_DIR = "./test"
